name: sigpr
version: 1.0.1
synopsis: Signal Program Runner
category: Development
build-type: Simple

dependencies:
- base
- unix
- directory

executables:
  sigpr:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -Wall
    - -threaded
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wredundant-constraints
    - -freverse-errors
