name: sigpr
version: 1.0.1
synopsis: Signal Program Runner
category: Development
build-type: Simple

dependencies:
- base
- unix > 2 && < 3
- directory > 1 && < 2

executables:
  sigpr:
    main:                Main.hs
    source-dirs:         src
    cc-options: -static
    ld-options: -static -pthread
    ghc-options:
    - -Wall
    - -O2
    - -static
    - -threaded
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wredundant-constraints
    - -freverse-errors
